language: csharp
solution: SerialActivator.sln
script:    # the following commands are just examples, use whatever your build process requires
  - ./build.sh
  - ./test.sh
  - grep "Test Results" build.log
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore SerialActivator.sln